package dialogue;

import controle.modele.ModeleArticle;
import entite.Article;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class FenChoixArticle extends javax.swing.JDialog {
    private ModeleArticle leModeleArticle = new ModeleArticle();
    public FenChoixArticle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        complementGUI();
    }

    private void complementGUI() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass()
                .getResource("/images/logoNetBeans.png")));
        setTitle("SARL XELFI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable(leModeleArticle);
        jLab_recherche = new javax.swing.JLabel();
        jTxT_Rechercher = new javax.swing.JTextField();
        jLabel_Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titre.setText("Double-cliquez sur la ligne de l'article.");
        jLabel_Titre.setToolTipText("");
        getContentPane().add(jLabel_Titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, -1, -1));

        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 656, 269));

        jLab_recherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesgestion/chercheAssiste.png"))); // NOI18N
        jLab_recherche.setText("Rechercher");
        jLab_recherche.setToolTipText("");
        getContentPane().add(jLab_recherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 322, 100, -1));

        jTxT_Rechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxT_RechercherKeyReleased(evt);
            }
        });
        getContentPane().add(jTxT_Rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 327, 125, -1));

        jLabel_Fond.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Fond.setOpaque(true);
        getContentPane().add(jLabel_Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 370));

        setSize(new java.awt.Dimension(698, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxT_RechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxT_RechercherKeyReleased
        Article unArticle = new Article("");
        ArrayList<Article> nouvelleListe =
                unArticle.chercherCRUD(jTxT_Rechercher.getText());
        leModeleArticle.lireRecupMode(nouvelleListe);
    }//GEN-LAST:event_jTxT_RechercherKeyReleased

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
            int ligne = jTable.getSelectedRow();
            if (Integer.valueOf(jTable.getValueAt(ligne, 3).toString()) == 0) {
                JOptionPane.showMessageDialog(null,
                        "Stock épuisé pour cet article",
                        "Ajout", JOptionPane.WARNING_MESSAGE);
            } else {
                FenFacture.setjTxT_CodeArticle(jTable.getValueAt(ligne, 0).toString());
                FenFacture.setjTxT_CodeCategorie(jTable.getValueAt(ligne, 1).toString());
                FenFacture.setjTxT_Designation(jTable.getValueAt(ligne, 2).toString());
                FenFacture.setjCmB_Quantite(Integer.valueOf(jTable.getValueAt(ligne, 3).toString()));
                FenFacture.setjTxT_Montant(jTable.getValueAt(ligne, 4).toString());
                FenChoixArticle.this.dispose();
            }
        }
    }//GEN-LAST:event_jTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Minus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenChoixArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenChoixArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenChoixArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenChoixArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FenChoixArticle dialog = new FenChoixArticle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLab_recherche;
    private javax.swing.JLabel jLabel_Fond;
    private javax.swing.JLabel jLabel_Titre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxT_Rechercher;
    // End of variables declaration//GEN-END:variables
}
