
package dialogue;

import controle.modele.ModeleClient;
import javax.swing.JLabel;
import javax.swing.JTextField;
import controle.utilitaires.GestionDates;
import entite.Client;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author MODESTE
 */
public class FenFicheClient extends javax.swing.JFrame implements TableModelListener {
 private ModeleClient leModeleClients = new ModeleClient();
    private String code_client;
    
    public FenFicheClient(ModeleClient modeleClientsTransmis, 
                                                      String demande) {
        initComponents();
        leModeleClients = modeleClientsTransmis;
        actionDemande = demande;
        leModeleClients.addTableModelListener(this);
    }

    private FenFicheClient() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    public JLabel getjLabTitreClient() {
        return jLabTitreClient;
    }

    public JLabel getjLab_Action() {
        return jLab_Action;
    }

    public JTextField getjTxTCode() {
        return jTxTCode;
    }

    public static JLabel getJTxT_DateCreation() {
        return jTxT_DateCreation;
    }

    public void setJTxTNom(String vNom) {
        jTxTNom.setText(vNom);
    }

    public void setJTxT_Prenom(String vPrenom) {
        jTxT_Prenom.setText(vPrenom);
    }

    public void setCheckBox_Carte(boolean bState) {
        checkBox_Carte.setState(bState);
    }

    public void setjTxTCode(String vCode) {
        jTxTCode.setText(vCode);
    }
    
    public void setJTXT_DateCreation(String vDate) {
        jTxT_DateCreation.setText(vDate);
    }

    public JLabel getjLabel4() {
        return jLab_Retour;
    }
    
    
    
    // private ModeleClient leModeleClients = null;
    private String actionDemande = "";
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTxTCode = new javax.swing.JTextField();
        jTxTNom = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTxT_Prenom = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        checkBox_Carte = new java.awt.Checkbox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable(leModeleClients);
        jPanel1 = new javax.swing.JPanel();
        jLab_Action = new javax.swing.JLabel();
        jLab_Retour = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabTitreClient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(830, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Code");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 20, 40, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nom");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 60, 30, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Adesse");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 100, 41, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Code postal");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 130, 66, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Tel.fix");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 180, 34, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Email");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 220, 30, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Remarques");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 250, 73, 14);
        jPanel2.add(jTxTCode);
        jTxTCode.setBounds(100, 10, 180, 30);

        jTxTNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxTNomActionPerformed(evt);
            }
        });
        jPanel2.add(jTxTNom);
        jTxTNom.setBounds(100, 50, 180, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(100, 90, 490, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(100, 130, 179, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(100, 170, 179, 30);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6);
        jTextField6.setBounds(100, 210, 179, 30);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(100, 250, 489, 51);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Date creation");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(298, 12, 77, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Prenom");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(300, 60, 77, 14);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("ville");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(310, 140, 51, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("mobillis");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(310, 180, 43, 14);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(380, 130, 211, 30);
        jPanel2.add(jTxT_Prenom);
        jTxT_Prenom.setBounds(380, 50, 209, 30);
        jPanel2.add(jTextField11);
        jTextField11.setBounds(380, 170, 211, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Carte fidelite");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(480, 10, 73, 14);

        jTxT_DateCreation.setForeground(new java.awt.Color(0, 0, 255));
        jTxT_DateCreation.setText("xxx");
        jPanel2.add(jTxT_DateCreation);
        jTxT_DateCreation.setBounds(381, 9, 91, 20);

        checkBox_Carte.setLabel("checkbox1");
        jPanel2.add(checkBox_Carte);
        checkBox_Carte.setBounds(570, 9, 20, 20);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 600, 320));

        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 600, 110));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLab_Action.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLab_Action.setForeground(new java.awt.Color(255, 255, 255));
        jLab_Action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-download.png"))); // NOI18N
        jLab_Action.setText("Ajouter:je vais changer");
        jLab_Action.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab_ActionMouseClicked(evt);
            }
        });
        jPanel1.add(jLab_Action, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));

        jLab_Retour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLab_Retour.setForeground(java.awt.Color.white);
        jLab_Retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-deny.png"))); // NOI18N
        jLab_Retour.setText("Annul");
        jLab_Retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab_RetourMouseClicked(evt);
            }
        });
        jPanel1.add(jLab_Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-preview.png"))); // NOI18N
        jLabel5.setText("Apercu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-print.png"))); // NOI18N
        jLabel6.setText("Imprimer");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-language.png"))); // NOI18N
        jLabel7.setText("Exporter");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-frontpage.png"))); // NOI18N
        jLabel8.setText("Menu principal");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 540));

        jLabTitreClient.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabTitreClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-48-user-add.png"))); // NOI18N
        jLabTitreClient.setText("je vais changer......");
        getContentPane().add(jLabTitreClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 500, 50));

        setSize(new java.awt.Dimension(848, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxTNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxTNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxTNomActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jLab_ActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_ActionMouseClicked
        String vCode = jTxTCode.getText();
        String vNom = jTxTNom.getText();
        String vPrenom = jTxT_Prenom.getText();
        boolean bCarteFidele = checkBox_Carte.getState();
        String strDate = jTxT_DateCreation.getText();
        int iCarteFidele;
        if (bCarteFidele == true) {
            iCarteFidele = 1;
        } else {
            iCarteFidele = 0;
        }
        if (actionDemande.equals("Ajouter")) {
            if (!vCode.equals("")) {
                String strDateMySQL = 
                        GestionDates.chaineDateFRversEN(strDate);
                Date dtDate = new Date();
                dtDate = GestionDates.dateJavaEnDateSQL(dtDate);
                Client leClient = new Client(vCode, vNom,
                        vPrenom, bCarteFidele, dtDate);
                boolean bCreation = false;
                bCreation = leClient.creerCRUD(vCode, vNom,
                        vPrenom, iCarteFidele, strDateMySQL);
                if (bCreation) {
                    leModeleClients.creerMOD(leClient);
                }
                jTxTCode.setText("");
                jTxTNom.setText("");
                jTxT_Prenom.setText("");
                checkBox_Carte.setState(false);
                jTxT_DateCreation.setText("");
                jTxTCode.requestFocus();
                dtDate = new Date();
                jTxT_DateCreation.setText(GestionDates
                        .dateEnChaineFR(dtDate));
            } else {
                JOptionPane.showMessageDialog(null,
                        "La saisie du code client"
                        + " est obligatoire",
                        "Vérifiez votre saisie",
                        JOptionPane.ERROR_MESSAGE);
            }
        }

        if (actionDemande.equals("Modifier")) {
            strDate = GestionDates
                    .chaineDateFRversEN(strDate);
            try {
                Date dtDate = GestionDates
                        .chaineENversDateJava(strDate);
                dtDate = GestionDates
                        .dateJavaEnDateSQL(dtDate);
                Client leClient = new Client(vCode, vNom,
                        vPrenom, bCarteFidele, dtDate);
                boolean bCreation = false;
                bCreation = leClient.modifierCRUD(vCode,
                        vNom, vPrenom, iCarteFidele, strDate);						
                if (bCreation) {
                    int numLigne = leModeleClients
                            .getNumLigne(vCode);
                    leModeleClients
                            .setValueAt(vCode,
                            numLigne, 0);
                    leModeleClients
                            .setValueAt(vNom,
                            numLigne, 1);
                    leModeleClients
                            .setValueAt(vPrenom,
                            numLigne, 2);
                    leModeleClients
                            .setValueAt(bCarteFidele,
                            numLigne, 3);
                    leModeleClients
                            .setValueAt(dtDate, numLigne, 4);
                    leModeleClients
                            .modifierMOD(numLigne,
                                         numLigne, leClient);
                    dispose();
                }
            } catch (ParseException e) {
                e.printStackTrace();
            }
        }

        if (actionDemande.equals("Rechercher")) {
            entite.Client leClient = new entite.Client(vCode);              
            ArrayList<Client> nouvelleListe = 
                  leClient.chercherCRUD(vCode, vNom, vPrenom);
            leModeleClients.lireRecupMOD(nouvelleListe);
        }
    }//GEN-LAST:event_jLab_ActionMouseClicked

    private void jLab_RetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_RetourMouseClicked
       FenTableClient laFenetre = new FenTableClient();
        laFenetre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLab_RetourMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        FenMenuPrincipal laFenetre = new FenMenuPrincipal();
        laFenetre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenFicheClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenFicheClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkBox_Carte;
    private javax.swing.JLabel jLabTitreClient;
    private javax.swing.JLabel jLab_Action;
    private javax.swing.JLabel jLab_Retour;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTxTCode;
    private javax.swing.JTextField jTxTNom;
    public static final transient javax.swing.JLabel jTxT_DateCreation = new javax.swing.JLabel();
    private javax.swing.JTextField jTxT_Prenom;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
         String suiteMessage = "\nFaisons d'autres actions"
                + " suite à cet événement.";
        switch (unEvenement.getType()) {
            case TableModelEvent.INSERT:
                System.out.println("La table a été mise à jour, "
                        + "il y a eu une insertion !!!"
                        + suiteMessage);
                break;
            case TableModelEvent.DELETE:
                System.out.println("La table a été mise à jour, "
                        + " il y a eu une suppression !!!"
                        + suiteMessage);
                break;
            case TableModelEvent.UPDATE:
                System.out.println("La table a été mise à jour, "
                        + "il y a eu une modification !!!"
                        + suiteMessage);
                break;
            default:
                break;
        }
    }
}
